language: android

jdk:
 - oraclejdk7
 - oraclejdk8

android:
  components:
    - android-22
    - build-tools-22.0.1
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-x86-android-22

before_script:
    - GRADLE_OPTS="-Xms1g -Xmx3g -XX:MaxPermSize=3g"

script: "./gradlew clean check -Dpre-dex=false"

branches:
  except:
    - gh-pages

sudo: false
