language: android

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.2
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-x86-android-22

jdk:
 - oraclejdk7
 - oraclejdk8

before_script:
    - GRADLE_OPTS="-Xms1g -Xmx3g -XX:MaxPermSize=3g"

script: "./gradlew clean check"

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.gradle
